feat: add-item-requests
AlexOdnoshivkin/java-shareit pull request #4
Opened 2022-10-17 01:18 UTC by AlexOdnoshivkin

2022-10-17 12:15 UTC, kukolev requested changes

2022-10-17 12:15 UTC, kukolev commented on src/main/java/ru/practicum/shareit/request/dto/ItemRequestMapper.java
> +    ;
Это лучше перенести сразу за скобку выше. Так будет привычней.

2022-10-17 12:15 UTC, kukolev commented on src/test/java/ru/practicum/shareit/booking/BookingControllerTest.java
> +    BookingService bookingService;
Нарушен принцип инкапсуляции. Поля класса не должны быть видимы другим классам. Лучше сделать поле приватным и сделать геттер и сеттер для полей, если нужен доступ извне.

2022-10-17 12:15 UTC, kukolev commented on src/test/java/ru/practicum/shareit/booking/Service/BookingServiceImplTest.java
> +    void addBooking() {
Этот тест нужно разбить на несколько небольших тестов, каждый из которых проверяет что-то конкретное. Хороший юнит тест состоит из трех блоков кода:

1. Подготовка данных для теста
2. Вызов тестируемого метода
3. Проверка результатов

Важно, чтобы п.2 выполнялся однократно - так будет проще понять что пошло не так, если один или несколько тестов упадут.

Подробнее о хороших практиках юнит-тестирования можно прочитать тут:  https://www.baeldung.com/java-unit-testing-best-practices

Аналогично нужно поправить и в других подобных тестах.

2022-10-17 12:15 UTC, kukolev commented on src/test/java/ru/practicum/shareit/booking/Service/BookingServiceImplTest.java
> +        try {
Вместо этой конструкции нужно использовать assertThrows. Текущий код может работать некорректно, если метода addBooking не будет кидать эксепшен - проверка в блоке catch не сработает.

Аналогично нужно поправить и в остальных тестах.

2022-10-17 12:15 UTC, kukolev commented on src/test/java/ru/practicum/shareit/item/ItemControllerTest.java
> +    ItemService itemService;
Нарушен принцип инкапсуляции. Поля класса не должны быть видимы другим классам. Лучше сделать поле приватным и сделать геттер и сеттер для полей, если нужен доступ извне.

2022-10-17 12:15 UTC, kukolev commented on src/test/java/ru/practicum/shareit/user/UserControllerTest.java
> +    UserService userService;
Нарушен принцип инкапсуляции. Поля класса не должны быть видимы другим классам. Лучше сделать поле приватным и сделать геттер и сеттер для полей, если нужен доступ извне.

2022-10-17 20:58 UTC, AlexOdnoshivkin commented
Исправил замечания по первому ревью

2022-10-18 08:02 UTC, kukolev requested changes

2022-10-18 08:02 UTC, kukolev commented on src/test/java/ru/practicum/shareit/item/ItemControllerTest.java
> +        try {
Не исправлено замечание: https://github.com/AlexOdnoshivkin/java-shareit/pull/4#discussion_r996981387
Нужно исправить.

2022-10-18 08:02 UTC, kukolev commented on src/test/java/ru/practicum/shareit/request/ItemRequestControllerTest.java
> +        try {
Не исправлено замечание: https://github.com/AlexOdnoshivkin/java-shareit/pull/4#discussion_r996981387
Нужно исправить.

2022-10-18 08:02 UTC, kukolev commented on src/test/java/ru/practicum/shareit/request/ItemRequestControllerTest.java
> +        try {
Не исправлено замечание: https://github.com/AlexOdnoshivkin/java-shareit/pull/4#discussion_r996981387
Нужно исправить.

2022-10-19 08:10 UTC, kukolev requested changes

2022-10-19 08:10 UTC, kukolev commented on src/test/java/ru/practicum/shareit/item/ItemControllerTest.java
> +        assertEquals(thrown.getMessage(), "Request processing failed; nested exception is " +
Тут и в остальных подобных случаях нужно поменять местами аргументы в assertEquals. Первый аргумент - expected, то значение, которое ожидается, а второй аргумент - actual, то значение, которое хотим проверить. Это мелочь, но это правила хорошего тона, к которым лучше привыкать сразу.

2022-10-19 17:18 UTC, kukolev approved these changes

2022-10-22 16:27 UTC, merged